apiVersion: v1
kind: Namespace
metadata:
  name: team5-slacktistics
  labels:
    app.kubernetes.io/component: slacktistics
    app.kubernetes.io/name: slacktistics
    app.kubernetes.io/part-of: slacktistics
    environment: hackternoon

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slacktistics
  namespace: team5-slacktistics
  annotations:
    app.kubernetes.io/version: "0.1"
  labels:
    app.kubernetes.io/component: slacktistics
    app.kubernetes.io/name: slacktistics
    app.kubernetes.io/part-of: slacktistics
    environment: hackternoon
spec:
  schedule: '0 0 16 * 5'
  concurrencyPolicy: 'Forbid'
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      annotations:
        app.kubernetes.io/version: "0.1"
      labels:
        app.kubernetes.io/component: slacktistics
        app.kubernetes.io/name: slacktistics
        app.kubernetes.io/part-of: slacktistics
        environment: hackternoon
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: slacktistics
              image: "${SLACKTISTICS_IMAGE}"
              imagePullPolicy: Always
              env:
                - name: SLACK_BOT_TOKEN
                  value: "${SLACK_BOT_TOKEN}"
